<title>SuperVoyage</title>
    <!--header-->
    <?php 
    include("pages\header+footer\header.php");
    ?>
        <br>
            <br>
                <br>
                    <br>
    <!--voyages-->
    <?php
    include("pages\produits\Voyages.php");
    ?>
        <br>
    <!--footer-->
    <?php 
    include("pages\header+footer\Footer.html");
    ?>
